apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java11
  template:
    metadata:
      labels:
        app: hello-java11
    spec:
      containers:
        - name: hello-java11
          image: hello-java11:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java11
spec:
  selector:
    app: hello-java11
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
