apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java17
  template:
    metadata:
      labels:
        app: hello-java17
    spec:
      containers:
        - name: hello-java17
          image: hello-java17:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java17
spec:
  selector:
    app: hello-java17
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
